#!/bin/bash

# IntelliJ IDEA Ultimate
function install_idea_ultimate {	
	# Variables
	NAME="IntelliJ IDEA"
	FILE_NAME="ideaIU-2019.1.tar.gz"
	REMOTE="https://download.jetbrains.com/idea"	
	#https://download.jetbrains.com/idea/ideaIC-2019.1.tar.gz

	# Download and unpacking remote package
	echo_message info "Downloading remote file '${FILE_NAME}' from '${REMOTE}'..."
	curl -OL ${REMOTE}/${FILE_NAME}
	superuser_do "tar xf ${FILE_NAME} -C /opt"

	rm ${FILE_NAME}
}