#!/bin/bash

# Skype
function install_skype {
	# Variables
	NAME="Skype"
	PACKAGE="skypeforlinux"
	ARCH=$(get_arch_postfix install_thirdparty)
	DEB_FILE_NAME="${PACKAGE}_8.42.76.54_${ARCH}.deb"
	REMOTE="https://repo.skype.com/deb/pool/main/s/skypeforlinux"

	# Download and install remote package
	install_remote_package $NAME $PACKAGE $REMOTE $DEB_FILE_NAME install_thirdparty
}