#!/bin/bash

# Slack
function install_slack {
	# Variables
	NAME="Slack"
	PACKAGE="slack-desktop"
	ARCH=$(get_arch_postfix install_thirdparty)
	DEB_FILE_NAME="${PACKAGE}-3.3.8-${ARCH}.deb"
	REMOTE="https://downloads.slack-edge.com/linux_releases"

	# Download and install remote package
	install_remote_package $NAME $PACKAGE $REMOTE $DEB_FILE_NAME install_thirdparty
}